apiVersion: apps/v1
kind: Deployment
metadata:
  name: docs-deployment
  labels:
    app: docs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docs
  template:
    metadata:
      labels:
        app: docs
    spec:
      containers:
      - name: docs
        image: degas1980/harness-demo:docs-latest
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  name: docs-service
spec:
  type: NodePort
  selector:
    app: docs
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30001
